"""Añadir tablas Usuario, Aula, RegistroAsistencia

Revision ID: 630efa5890da
Revises: 
Create Date: 2025-04-18 14:26:47.405184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '630efa5890da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('aula_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aula_id'], ['aula.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('registro_asistencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registro_asistencia')
    op.drop_table('usuario')
    op.drop_table('aula')
    # ### end Alembic commands ###
